### ISSUE TITLE
Pruning sources from previous analysis, due to incompatible CompileSetup.

### ISSUE THREAD

**Issue by timur-perelmutov** [gradle-guides/building-scala-libraries#3]
compileScala and compileTestScala tasks outputs documented at https://guides.gradle.org/building-scala-libraries/ contains the following warning : "Pruning sources from previous analysis, due to incompatible CompileSetup." I observed the same outputs in my project's build output. Could this be documented why the output is produced by these tasks? Is this an expected output?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #245](https://github.com/gradle/guides/issues/245) via [**ZenHub**](https://www.zenhub.com/)
